# Generated by Django 5.1.3 on 2024-12-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
