# Generated by Django 5.1.3 on 2024-12-02 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_obra_data_modificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='data_modificacao',
        ),
    ]
