# Generated by Django 5.1.3 on 2024-12-02 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_remove_obra_data_modificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
